import fs from "node:fs";
import path from "node:path";

import {
  buildClaudeMcpConfig,
  buildClaudeSettingsConfig,
  buildCodexMcpConfig,
  buildGeminiSettingsConfig,
  DEFAULT_REPORAG_CONFIG,
  REPORAG_MCP_SERVER_NAME,
  type InitResult,
  type McpCommandConfig,
  PROJECT_MCP_WRAPPER_RELATIVE_PATH,
  PROJECT_CLAUDE_SHARED_SETTINGS_RELATIVE_PATH,
  type ReporagConfig,
  parseReporagConfig,
} from "@reporag/shared";
import { ensureDatabase, ensureReporagLayout } from "@reporag/adapters";

const REPORAG_SKILL_RELATIVE_DIR = ".codex/skills/reporag-mcp-usage";
const REPORAG_SKILL_RELATIVE_PATH = `${REPORAG_SKILL_RELATIVE_DIR}/SKILL.md`;
const AGENTS_FILENAME = "AGENTS.md";
const CLAUDE_FILENAME = "CLAUDE.md";
const REPORAG_CLAUDE_GUIDANCE_RELATIVE_PATH = ".claude/reporag-mcp.md";
const AGENTS_BLOCK_START =
  "<!-- BEGIN reporag managed repository_rag guidance -->";
const AGENTS_BLOCK_END =
  "<!-- END reporag managed repository_rag guidance -->";
const CLAUDE_BLOCK_START =
  "<!-- BEGIN reporag managed Claude repository_rag guidance -->";
const CLAUDE_BLOCK_END =
  "<!-- END reporag managed Claude repository_rag guidance -->";

function detectRepoRoot(startDir: string): string {
  const initial = path.resolve(startDir);
  let current = initial;
  let nearestReporagRoot: string | null = null;
  const packageJsonRoots: string[] = [];

  while (true) {
    if (fs.existsSync(path.join(current, ".git"))) {
      return current;
    }

    if (fs.existsSync(path.join(current, ".reporag"))) {
      nearestReporagRoot = current;
    }

    if (fs.existsSync(path.join(current, "package.json"))) {
      packageJsonRoots.push(current);
    }

    const parent = path.dirname(current);
    if (parent === current) {
      break;
    }

    current = parent;
  }

  const highestPackageJsonRoot =
    packageJsonRoots.length > 0
      ? packageJsonRoots[packageJsonRoots.length - 1]
      : null;

  return nearestReporagRoot ?? highestPackageJsonRoot ?? initial;
}

function readConfig(configPath: string): ReporagConfig | null {
  if (!fs.existsSync(configPath)) {
    return null;
  }

  const raw = JSON.parse(fs.readFileSync(configPath, "utf8")) as unknown;
  return parseReporagConfig(raw);
}

function writeConfig(configPath: string, config: ReporagConfig): void {
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2), "utf8");
}

function buildReporagSkillSource(): string {
  return `---
name: reporag-mcp-usage
description: Use when a repo initialized by reporag needs guidance for the ${REPORAG_MCP_SERVER_NAME} MCP, MCP repo search, symbols, symbol lookup, callers, callees, busqueda estructural, quien llama, que llama, or structured repository navigation in English or Spanish.
---

# Reporag MCP Usage

Use the \`${REPORAG_MCP_SERVER_NAME}\` MCP conservatively for structured repository navigation before falling back to shell exploration.

## Tool choice

- Use \`get_symbol\` for exact symbols or when a symbol name may be ambiguous.
- Use \`find_callers\` for "who calls this".
- Use \`find_callees\` for "what this calls".
- Use \`search_code\` for text search, natural-language search, or when no stable symbol is known yet.

## Disambiguation

- Prefer \`path#symbol\` when the same symbol appears in multiple files, for example \`packages/app/src/mcp-server.ts#runMcpServer\`.
- Use \`Parent.symbol\` for methods or nested members, for example \`PlayerController.start\`.
- Combine both as \`path#Parent.symbol\` when you need file and container disambiguation at the same time.

## Reading results

- \`search_code\` may report \`route=symbol\`, \`route=fts\`, or \`route=hybrid\`; use that to judge precision.
- \`find_callers\` and \`find_callees\` may return multiple \`matchedSymbols\` before the final \`hits\`; treat that as ambiguity to resolve, not as the final call graph answer.
- Distinguish between "no useful hits" and "ambiguous symbol selector".

## Fallback

- If the MCP is unavailable, say so explicitly and continue with normal repo exploration.
- If you only see a \`repository_rag\` MCP talking about PostgreSQL, snapshots, or \`snapshot:index\`, that is not the local reporag server generated by \`init\`; prefer \`${REPORAG_MCP_SERVER_NAME}\`.
- If the results look stale or empty, suggest \`reporag index\`.
- If the MCP still does not help, fall back to direct file inspection.
`;
}

function buildAgentsManagedBlock(): string {
  return [
    AGENTS_BLOCK_START,
    "## Skills added by reporag",
    "",
    "This block is managed by `reporag init`.",
    "",
    `- \`reporag-mcp-usage\`: use for structured repository navigation and the \`${REPORAG_MCP_SERVER_NAME}\` MCP, including symbol lookup, callers, callees, and structured repo search. File: \`${REPORAG_SKILL_RELATIVE_PATH}\``,
    "- Fallback: if the MCP is missing, stale, or not returning useful context yet, run `reporag index` and continue with normal repo exploration.",
    AGENTS_BLOCK_END,
  ].join("\n");
}

function buildClaudeGuidanceSource(): string {
  return `# Reporag MCP Guidance

Use the \`${REPORAG_MCP_SERVER_NAME}\` MCP conservatively for structured repository navigation before falling back to normal file exploration.

## Tool choice

- Use \`get_symbol\` for exact symbol lookup and symbol disambiguation.
- Use \`find_callers\` to answer who calls a symbol.
- Use \`find_callees\` to answer what a symbol calls.
- Use \`search_code\` for textual or natural-language search when no stable symbol is known yet.

## Disambiguation

- Prefer \`path#symbol\` when the same symbol exists in multiple files, for example \`packages/app/src/mcp-server.ts#runMcpServer\`.
- Use \`Parent.symbol\` for methods or nested members, for example \`PlayerController.start\`.
- Combine both as \`path#Parent.symbol\` when you need file and container disambiguation at the same time.

## Reading results

- \`search_code\` may report \`route=symbol\`, \`route=fts\`, or \`route=hybrid\`.
- \`find_callers\` and \`find_callees\` may include multiple \`matchedSymbols\` before the final \`hits\`; treat that as ambiguity to resolve first.
- Distinguish between an ambiguous selector and a true no-results case.

## Fallback

- If the MCP is unavailable, say so explicitly and continue with normal repo exploration.
- If you only see a \`repository_rag\` MCP that talks about PostgreSQL, snapshots, or \`snapshot:index\`, that is not the local reporag server generated by \`init\`; prefer \`${REPORAG_MCP_SERVER_NAME}\`.
- If the results look stale or empty, suggest \`reporag index\`.
- If the MCP still does not help, inspect files directly.
`;
}

function buildClaudeManagedBlock(): string {
  return [
    CLAUDE_BLOCK_START,
    `Use \`${REPORAG_MCP_SERVER_NAME}\` for structured repository navigation before falling back to shell or raw file search.`,
    `@${REPORAG_CLAUDE_GUIDANCE_RELATIVE_PATH}`,
    CLAUDE_BLOCK_END,
  ].join("\n");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function upsertManagedBlock(
  current: string,
  blockStart: string,
  blockEnd: string,
  managedBlock: string,
  emptyFileTemplate: string,
): string {
  const normalized = current.replace(/\r\n/g, "\n");
  const managedBlockPattern = new RegExp(
    `${escapeRegExp(blockStart)}[\\s\\S]*?${escapeRegExp(blockEnd)}`,
    "u",
  );

  if (managedBlockPattern.test(normalized)) {
    return `${normalized.replace(managedBlockPattern, managedBlock).trimEnd()}\n`;
  }

  const trimmed = normalized.trim();
  if (trimmed.length === 0) {
    return emptyFileTemplate;
  }

  return `${normalized.trimEnd()}\n\n${managedBlock}\n`;
}

function upsertManagedAgentsBlock(current: string): string {
  return upsertManagedBlock(
    current,
    AGENTS_BLOCK_START,
    AGENTS_BLOCK_END,
    buildAgentsManagedBlock(),
    `# AGENTS\n\n${buildAgentsManagedBlock()}\n`,
  );
}

function upsertManagedClaudeBlock(current: string): string {
  return upsertManagedBlock(
    current,
    CLAUDE_BLOCK_START,
    CLAUDE_BLOCK_END,
    buildClaudeManagedBlock(),
    `# CLAUDE\n\n${buildClaudeManagedBlock()}\n`,
  );
}

function ensureAgentGuidance(repoRoot: string): void {
  const skillPath = path.join(
    repoRoot,
    ".codex",
    "skills",
    "reporag-mcp-usage",
    "SKILL.md",
  );
  const agentsPath = path.join(repoRoot, AGENTS_FILENAME);
  const existingAgents = fs.existsSync(agentsPath)
    ? fs.readFileSync(agentsPath, "utf8")
    : "";

  fs.mkdirSync(path.dirname(skillPath), { recursive: true });
  fs.writeFileSync(skillPath, buildReporagSkillSource(), "utf8");
  fs.writeFileSync(agentsPath, upsertManagedAgentsBlock(existingAgents), "utf8");
}

function ensureClaudeGuidance(repoRoot: string): void {
  const claudeGuidancePath = path.join(repoRoot, REPORAG_CLAUDE_GUIDANCE_RELATIVE_PATH);
  const claudeMemoryPath = path.join(repoRoot, CLAUDE_FILENAME);
  const existingClaudeMemory = fs.existsSync(claudeMemoryPath)
    ? fs.readFileSync(claudeMemoryPath, "utf8")
    : "";

  fs.mkdirSync(path.dirname(claudeGuidancePath), { recursive: true });
  fs.writeFileSync(claudeGuidancePath, buildClaudeGuidanceSource(), "utf8");
  fs.writeFileSync(
    claudeMemoryPath,
    upsertManagedClaudeBlock(existingClaudeMemory),
    "utf8",
  );
}

function ensureGitIgnore(repoRoot: string): void {
  const gitIgnorePath = path.join(repoRoot, ".gitignore");

  const current = fs.existsSync(gitIgnorePath)
    ? fs.readFileSync(gitIgnorePath, "utf8")
    : "";

  const requiredEntries = [
    ".reporag/",
    ".codex/config.toml",
    ".codex/skills/reporag-mcp-usage/",
    ".mcp.json",
    ".claude/settings.local.json",
    ".claude/settings.json",
    ".gemini/settings.json",
  ];
  const normalizedLines = new Set(
    current
      .split(/\r?\n/u)
      .map((line) => line.trim())
      .filter((line) => line.length > 0),
  );
  const missingEntries = requiredEntries.filter(
    (entry) => !normalizedLines.has(entry) && !normalizedLines.has(`/${entry}`),
  );

  if (missingEntries.length === 0) {
    return;
  }

  const prefix =
    current.length > 0 && !current.endsWith("\n") ? `${current}\n` : current;
  const next = `${prefix}${missingEntries.join("\n")}\n`;

  fs.writeFileSync(gitIgnorePath, next, "utf8");
}

function writeJsonFile(filePath: string, value: Record<string, unknown>): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function resolveMcpServerEntryPath(
  repoRoot: string,
  cliEntryPath?: string,
): string | null {
  const candidates = [
    cliEntryPath,
    path.join(repoRoot, "packages", "cli", "bundle", "reporag.cjs"),
    path.join(repoRoot, "packages", "cli", "dist", "cli.js"),
    path.join(process.cwd(), "packages", "cli", "bundle", "reporag.cjs"),
    path.join(process.cwd(), "packages", "cli", "dist", "cli.js"),
  ].filter((candidate): candidate is string => Boolean(candidate));

  for (const candidate of candidates) {
    const absoluteCandidate = path.resolve(candidate);
    if (fs.existsSync(absoluteCandidate)) {
      return fs.realpathSync(absoluteCandidate);
    }
  }

  return null;
}

function buildMcpWrapperSource(repoRoot: string, cliRuntimePath: string): string {
  return [
    "const { spawn } = require('node:child_process');",
    "",
    `const repoRoot = ${JSON.stringify(repoRoot)};`,
    `const cliRuntimePath = ${JSON.stringify(cliRuntimePath)};`,
    "",
    "const child = spawn(",
    "  process.execPath,",
    "  [cliRuntimePath, 'mcp', 'serve'],",
    "  {",
    "    cwd: repoRoot,",
    "    env: { ...process.env, REPORAG_REPO_ROOT: repoRoot },",
    "    stdio: 'inherit',",
    "  },",
    ");",
    "",
    "const forwardSignal = (signal) => {",
    "  if (!child.killed) {",
    "    child.kill(signal);",
    "  }",
    "};",
    "",
    "process.once('SIGINT', () => {",
    "  forwardSignal('SIGINT');",
    "});",
    "",
    "process.once('SIGTERM', () => {",
    "  forwardSignal('SIGTERM');",
    "});",
    "",
    "child.on('exit', (code, signal) => {",
    "  if (signal) {",
    "    process.kill(process.pid, signal);",
    "    return;",
    "  }",
    "",
    "  process.exit(code ?? 1);",
    "});",
    "",
    "child.on('error', (error) => {",
    "  console.error('Failed to launch reporag MCP server:', error);",
    "  process.exit(1);",
    "});",
    "",
  ].join("\n");
}

function ensureMcpWrapper(repoRoot: string, cliEntryPath?: string): string {
  const wrapperPath = path.join(repoRoot, PROJECT_MCP_WRAPPER_RELATIVE_PATH);
  const cliRuntimePath = resolveMcpServerEntryPath(repoRoot, cliEntryPath);

  if (!cliRuntimePath) {
    throw new Error("Unable to locate reporag CLI runtime for MCP wrapper generation");
  }

  fs.mkdirSync(path.dirname(wrapperPath), { recursive: true });
  fs.writeFileSync(
    wrapperPath,
    buildMcpWrapperSource(repoRoot, cliRuntimePath),
    "utf8",
  );

  return wrapperPath;
}

function resolveMcpCommandConfig(
  repoRoot: string,
  cliEntryPath?: string,
): McpCommandConfig {
  const wrapperPath = ensureMcpWrapper(repoRoot, cliEntryPath);

  return {
    command: process.execPath,
    args: [wrapperPath],
    cwd: repoRoot,
  };
}

function ensureMcpClientConfigs(repoRoot: string, cliEntryPath?: string): void {
  const codexPath = path.join(repoRoot, ".codex", "config.toml");
  const claudeMcpPath = path.join(repoRoot, ".mcp.json");
  const claudeSettingsPath = path.join(repoRoot, ".claude", "settings.local.json");
  const claudeSharedSettingsPath = path.join(
    repoRoot,
    PROJECT_CLAUDE_SHARED_SETTINGS_RELATIVE_PATH,
  );
  const geminiSettingsPath = path.join(repoRoot, ".gemini", "settings.json");
  const mcpCommand = resolveMcpCommandConfig(repoRoot, cliEntryPath);

  fs.mkdirSync(path.dirname(codexPath), { recursive: true });
  fs.writeFileSync(codexPath, buildCodexMcpConfig(mcpCommand), "utf8");
  writeJsonFile(claudeMcpPath, buildClaudeMcpConfig(mcpCommand));
  writeJsonFile(claudeSettingsPath, buildClaudeSettingsConfig());
  writeJsonFile(claudeSharedSettingsPath, buildClaudeSettingsConfig());

  const existingGeminiSettings = fs.existsSync(geminiSettingsPath)
    ? (JSON.parse(fs.readFileSync(geminiSettingsPath, "utf8")) as Record<string, unknown>)
    : null;
  writeJsonFile(
    geminiSettingsPath,
    buildGeminiSettingsConfig(existingGeminiSettings, mcpCommand),
  );
}

export function initRepository(startDir: string, cliEntryPath?: string): InitResult {
  try {
    const repoRoot = detectRepoRoot(startDir);

    const { repoDir, dbPath } = ensureReporagLayout(repoRoot);
    const configPath = path.join(repoDir, "config.json");

    const alreadyInitialized = fs.existsSync(configPath);
    const nextConfig = alreadyInitialized
      ? readConfig(configPath) ?? parseReporagConfig(DEFAULT_REPORAG_CONFIG)
      : parseReporagConfig(DEFAULT_REPORAG_CONFIG);

    writeConfig(configPath, nextConfig);

    ensureDatabase(dbPath);
    ensureMcpClientConfigs(repoRoot, cliEntryPath);
    ensureAgentGuidance(repoRoot);
    ensureClaudeGuidance(repoRoot);
    ensureGitIgnore(repoRoot);

    return {
      ok: true,
      repoRoot,
      configPath,
      dbPath,
      alreadyInitialized,
    };
  } catch (error) {
    const repoRoot = detectRepoRoot(startDir);

    return {
      ok: false,
      repoRoot,
      errorCode: "FS_ERROR",
      message:
        error instanceof Error ? error.message : "Unknown error during init",
    };
  }
}
